In [1]:
# بسم الله الرحمن الرحيم
# (وما توفيقى الا بالله)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv(r"C:\Users\moham\Downloads\workspace (1)\workspace\production_data.csv")

df.head()

,batch_id,production_date,raw_material_supplier,pigment_type,pigment_quantity,mixing_time,mixing_speed,product_quality_score
0,1,2024-06-25,1,type_a,42.822881,22.56,High,7.165102
1,2,2023-11-23,2,type_b,42.873479,44.97,High,6.849126
2,3,2024-02-18,2,type_b,33.251206,52.62,High,5.661209
3,4,2023-11-11,1,type_a,52.532817,24.96,High,6.991735
4,5,2024-04-11,2,type_c,36.205108,25.37,High,7.095043

Task 1:Cleaning Steps

In [2]:
## Parsing Date

df['production_date']= pd.to_datetime(df['production_date'])

## raw_material_supplier COl


df['raw_material_supplier'] = df['raw_material_supplier'].replace(1, 'national_supplier')
df['raw_material_supplier'] = df['raw_material_supplier'].replace(2, 'international_supplier')
df['raw_material_supplier'] = df['raw_material_supplier'].astype(str)

## pigment_type Col

df['pigment_type'] = df['pigment_type'].replace('Type_C','type_c') 

## pigment_quantity

df['pigment_quantity'] = df['pigment_quantity'].astype(int)

# pigment_quantity

df['pigment_quantity'] = df['pigment_quantity'].astype(int)

## mixing_time and filling NAN and rounding

df['mixing_time'].fillna(df['mixing_time'].mean(),inplace=True)
df['mixing_time'] = df['mixing_time'].round(2)

## mixing_speed Col 

df['mixing_speed'] = df['mixing_speed'].replace("-","Not Specified")

## product_quality_score

df['product_quality_score'] = df['product_quality_score'].round(2)


clean_data = df

clean_data.head()

C:\Users\moham\AppData\Local\Temp\ipykernel_18080\987627079.py:26: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['mixing_time'].fillna(df['mixing_time'].mean(),inplace=True)

,batch_id,production_date,raw_material_supplier,pigment_type,pigment_quantity,mixing_time,mixing_speed,product_quality_score
0,1,2024-06-25,national_supplier,type_a,42,22.56,High,7.17
1,2,2023-11-23,international_supplier,type_b,42,44.97,High,6.85
2,3,2024-02-18,international_supplier,type_b,33,52.62,High,5.66
3,4,2023-11-11,national_supplier,type_a,52,24.96,High,6.99
4,5,2024-04-11,international_supplier,type_c,36,25.37,High,7.10

Task 2 : Calculate the average product_quality_score and pigment_quantity grouped by raw_material_supplier

In [6]:
aggregated_data = clean_data.groupby('raw_material_supplier').agg(
    avg_product_quality_score = ('product_quality_score','mean'),
    avg_pigment_quantity = ('pigment_quantity','mean')
).round(2).reset_index()


aggregated_data

    raw_material_supplier  avg_product_quality_score  avg_pigment_quantity
0  international_supplier                       5.97                 34.42
1       national_supplier                       8.02                 44.23

Task 3 : Identify the average product_quality_score for batches with a raw_material_supplier of 2 and a pigment_quantity greater than 35 kg.

1) Your output should be a DataFrame named pigment_data.
2) It should consist of a 1-row DataFrame with 3 columns: raw_material_supplier, pigment_quantity, and avg_product_quality_score.
3) Your answers should be rounded to 2 decimal places where appropriate.

In [4]:
# Write your answer to Task 3 here

filtered = clean_data[(clean_data['raw_material_supplier']=='international_supplier')&(clean_data['pigment_quantity']>35)]

pigment_data = filtered.groupby(['raw_material_supplier', 'pigment_quantity'])['product_quality_score'] \
    .mean().round(2).reset_index() \
    .rename(columns={'product_quality_score': 'avg_product_quality_score'})

pigment_data

     raw_material_supplier  pigment_quantity  avg_product_quality_score
0   international_supplier                36                       6.08
1   international_supplier                37                       5.81
2   international_supplier                38                       5.95
3   international_supplier                39                       6.16
4   international_supplier                40                       6.10
5   international_supplier                41                       5.71
6   international_supplier                42                       5.93
7   international_supplier                43                       5.96
8   international_supplier                44                       5.89
9   international_supplier                45                       6.47
10  international_supplier                46                       6.03
11  international_supplier                47                       6.07
12  international_supplier                48                       6.72
13  international_supplier                49                       6.64

Task 4 : 
1) Calculate the mean and standard deviation for the columns pigment_quantity and product_quality_score as: product_quality_score_mean, product_quality_score_sd, pigment_quantity_mean, pigment_quantity_sd.
2) Calculate the Pearson correlation coefficient between pigment_quantity and product_quality_score as: corr_coef
Your output should be a DataFrame named product_quality.

In [5]:
# Write your answer to Task 4 here

product_quality_score_mean = clean_data['product_quality_score'].mean().round(2)
product_quality_score_sd = clean_data['product_quality_score'].std().round(2)
pigment_quantity_mean = clean_data['pigment_quantity'].mean().round(2)
pigment_quantity_sd = clean_data['pigment_quantity'].std().round(2)
corr_coef = clean_data['pigment_quantity'].corr(clean_data['product_quality_score']).round(2)

dict = {
    'product_quality_score_mean': [product_quality_score_mean],
    'product_quality_score_sd' : [product_quality_score_sd],
    'pigment_quantity_mean' : [pigment_quantity_mean],
    'pigment_quantity_sd' : [pigment_quantity_sd],
    'corr_coef' : corr_coef
}

product_quality = pd.DataFrame(dict)

product_quality

,product_quality_score_mean,product_quality_score_sd,pigment_quantity_mean,pigment_quantity_sd,corr_coef
0,6.68,1.39,37.85,6.83,0.49